DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.psm1, DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.schema.mof, Examples/Sample_xPfxImport_IIS_WebSite.ps1, Examples/Sample_xPfxImport_MinimalUsage.ps1, ReadMe.md, Tests/MSFT_xPfxImport.tests.ps1
Adds the `xPfxImport` resource, see https://github.com/PowerShell/DscResources/issues/58
=> Adding xPfxImport DSC Resource

DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, ReadMe.md
Hi, if the CA Root name contains space, certreq will fails. This Pr should fix the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/21)
=> Fix small bug related to CA rootname

Tests/Integration/MSFT_xCertReq.Integration.Tests.ps1, Tests/Integration/MSFT_xCertificateImport.Integration.Tests.ps1, Tests/Integration/MSFT_xPfxImport.Integration.Tests.ps1
Per PowerShell/DscResource.Tests#79 Install-ModuleFromPowerShellGallery from TestHelper.psm1 has been modified and 'WorkingFolder' has been removed from the test environment.
This PR fixes problems in this repo brought on by those changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/36)
=> Replace $TestEnvironment.WorkingFolder with $TestDrive

DSCResources/PDT/PDT.psm1
This function was not defined, but I think it should be calling New-InvalidArgumentError?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/34)
=> Incorrect function name

DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, ReadMe.md, Tests/Unit/MSFT_xCertReq.Tests.ps1
Adds code to Test-TargetResource to check that DNS Names in SANs are correct.
Does not handle other types of SANs, but a similar technique could probably be implemented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/62)
=> PR to fix issue 61 for DNS SANs

DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, DSCResources/MSFT_xCertificateExport/MSFT_xCertificateExport.psm1, DSCResources/MSFT_xCertificateImport/MSFT_xCertificateImport.psm1, DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.psm1, ReadMe.md, Tests/Integration/ModuleConflict.Tests.ps1, xCertificate.psd1
This resolves a high priority issue with newer versions of xNetworking, xCertificate, xStorage and xDFS conflicting with each other because the ResourceHelper cmdlets are being exported due to the way each resource imported them (using the PSD1 nested modules array).
This should be resolved in xNetworking, xStorage and xDFS as well to ensure no other conflicts.
This also contains a new integration test that will check for any further conflicts between resource modules. At some point it might be possible to move this test into the DSCResource.Tests common tests to provide more comprehensive conflict prevention. However, because the conflicts will potentially be between three different modules the number of modules compared will have to go in over time.
This fixes #64
---
This change …
=> Prevent ResourceHelper and Common cmdlets from being exported - Fixes #64

.vscode/settings.json, ReadMe.md
Added the VS Code PowerShell extension formatting settings that cause PowerShell files to be formatted as per the DSC Resource kit style guidelines. Fixes #71
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/72)
=> Added .vscode\settings.json with default VS Code PowerShell extension formatting settings - Fixes #71

Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, Modules/CertificateDsc.Common/en-us/CertificateDsc.Common.strings.psd1, ReadMe.md
The issue being fixed by this PR is that verbose messages in the Common functions would not be sent to the verbose stream, even if the resource is run with Verbose enabled.
This PR fixes that issue.
As discussed in: https://github.com/PowerShell/xSQLServer/issues/641
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/74)
=> Fixed verbose preference not being passed to CertificateDsc.Common functions - Fixes #70

DSCResources/MSFT_xCertificateImport/MSFT_xCertificateImport.psm1, DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.psm1, Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, Modules/CertificateDsc.PDT/CertificateDsc.PDT.psm1, ReadMe.md
This module was using several different functions to raise exceptions. This resulted in additional code and extra complexity.
This PR converts all exception calls to use the standard functions in CertificateDsc.ResourceHelper (which are copied from PSDscResources) and removes the no longer used function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/77)
=> Converted to use exception code in ResourceHelper module - Fixes #68

DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, DSCResources/MSFT_xCertReq/MSFT_xCertReq.schema.mof, LICENSE, ReadMe.md, xCertificate.psd1
Key Lengths of 1024 bits are now considered to broken. Therefore we should not be using that as the default key length.
See [Microsoft Security Advisory](https://support.microsoft.com/en-nz/help/2661254/microsoft-security-advisory-update-for-minimum-certificate-key-length).
This PR changes the default value to 1024 bits. Although in most cases this is not a **breaking change**, if users have been using the default key length then this may prevent some systems from using the certificates. Also, certificate templates may be setup that prohibit the issuance of more than 1024 bits (for one reason or another). So I think we should consider this a breaking change.
I also took this opportunity to correct the license info and copyright years in the Manifest and License to be 2017 and Microsoft …
=> BREAKING CHANGE: Change Default Key Length to 2048 bits in xCertReq - Fixes #82

CHANGELOG.md, Tests/TestHarness.psm1
Prevents the unit tests in the DSCResource.Tests helper from being executed during test execution.
@Johlju - would you mind reviewing this when you get a moment. Should be pretty straight forward.
Fixes #100
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/101)
=> Prevent unit tests in DSCResource.Tests from running - Fixes #100

CHANGELOG.md, Modules/xCertificate/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, Modules/xCertificate/DSCResources/MSFT_xCertReq/MSFT_xCertReq.schema.mof, Modules/xCertificate/DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.psm1, Modules/xCertificate/DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.schema.mof
- Changed description in Credential parameter of xPfxImport resource
to correctly generate parameter documentation in Wiki - see [Issue #103](https://github.com/PowerShell/xCertificate/issues/103).
- Changed description in Credential parameter of xCertReq resource
to clarify that a PSCredential object should be used.
Fixes #103
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/104)
=> Improve Wiki documentation generation for Credential parameters - Fixes #103

CHANGELOG.md, Modules/xCertificate/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, Modules/xCertificate/DSCResources/MSFT_xCertificateImport/MSFT_xCertificateImport.psm1, Modules/xCertificate/DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.psm1, Modules/xCertificate/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, Tests/Integration/CertificateDsc.Common.Tests.ps1, Tests/Unit/CertificateDsc.Common.Tests.ps1
AAdded support for WS 2008R2 for xCertificateImport and xPfxImport by adding simple
`Import-CertificateEx` and `Import-PfxCertificateEx` cmdlets that get executed if the ones in PKI do
not exist.
Fixes #46
**Task list:**
@Johlju - would you mind reviewing if you get a moment? No urgency!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/110)
=> Added support for WS 2008R2 for xCertificateImport and xPfxImport - Fixes #46

CHANGELOG.md, Modules/xCertificate/DSCResources/MSFT_xCertReq/MSFT_xCertReq.psm1, Modules/xCertificate/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, Tests/Unit/MSFT_xCertReq.Tests.ps1
Quote template name in certificate request
Fix Get-CertificateTemplateName to allow for spaces
#111
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/112)
=> xCertReq - Allow certificate templates with spaces in them

CHANGELOG.md, Modules/xCertificate/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1, Modules/xCertificate/Modules/CertificateDsc.Common/en-us/CertificateDsc.Common.strings.psd1
On my system, every time the DSC configuration runs xCertReq, a new certificate gets issued, because it can't match the template name. Fix: Query the template name from active directory if the template has no display name:
No issue, direct PR.
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/119)
=> Get-CertificateTemplateName: Fix missing template name

CHANGELOG.md, DSCResources/MSFT_CertificateExport/MSFT_CertificateExport.psm1, Tests/Integration/MSFT_CertificateExport.Integration.Tests.ps1
This PR fixes the error that occurs when using the CertificateExport to export a PFX with matchsource enabled. This PR replaces #117 .
- Fixes #116 
@johlju - would you mind reviewing when you get a chance?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/170)
=> Fix export of PFX with matchsource enabled - Fixes #116

CHANGELOG.md, DSCResources/MSFT_CertReq/MSFT_CertReq.psm1, DSCResources/MSFT_CertificateImport/MSFT_CertificateImport.psm1, Tests/Unit/MSFT_CertReq.Tests.ps1
- CertReq:
- Simplified unit test comparison certificate request strings to make
tests easier to read.
- Improved unit test layout and updated to meet standards.
- Fixed bug in certificate renewal with `RenewalCert` attribute in the
incorrect section - fixes [Issue 172](https://github.com/PowerShell/CertificateDsc/issues/172)
- Fixed bug in certificate renewal when subject contains X500 path that
is in a different order - fixes [Issue 173](https://github.com/PowerShell/CertificateDsc/issues/173)
- Fixes #172 
- Fixes #173
@johlju - would you be able to review this one when you get a moment? I ended up cleaning up the unit tests for CertReq as they weren't up to our normal standards.
--- …
=> CertReq: Fix X500 Subject Match and Renewal - Fixes #172

CHANGELOG.md, CertificateDsc.psd1, DSCResources/MSFT_CertReq/MSFT_CertReq.psm1, DSCResources/MSFT_CertReq/MSFT_CertReq.schema.mof, DSCResources/MSFT_CertReq/en-US/MSFT_CertReq.strings.psd1, Examples/Resources/CertReq/1-CertReq_RequestAltSSLCert_Config.ps1, Examples/Resources/CertReq/2-CertReq_RequestSSLCert_Config.ps1, Tests/Integration/MSFT_CertReq.Integration.Tests.ps1, Tests/Integration/MSFT_CertReq.config.ps1, Tests/Unit/MSFT_CertReq.Tests.ps1
Added parameter to choose if ECDH or RSA key types are being used in an effort to ensure the right key length is chosen. Added additional key lengths to support ECDH. 
Added parameter to change the request type to PKCS10 if needed. 
- Fixes #113 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/175)
=> CertificateDSC: Adding ECDH key lengths and Request Type PKCS10

CHANGELOG.md, DSCResources/MSFT_CertReq/MSFT_CertReq.psm1, Tests/Unit/MSFT_CertReq.Tests.ps1
Fixed exception when Certificate with empty Subject exists in Certificate Store. I also refactored some of the unit tests and removed some code duplication by adding a new function.
- #190
@johlju - would you mind reviewing this one for me when you have a moment?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/191)
=> Fixed exception when Certificate with empty Subject exists in Certificate Store - Fixes #190

CHANGELOG.md, DSCResources/MSFT_CertReq/MSFT_CertReq.psm1, Modules/CertificateDsc.Common/CertificateDsc.Common.psm1, README.md, Tests/Unit/CertificateDsc.Common.Tests.ps1, Tests/Unit/MSFT_CertReq.Tests.ps1
This PR resolves issues in CertReq where extension detection fails on non-US localized machines. This is because it was using the friendly name of the extension to match. It is now converted to use the Oid values instead.
I also cleaned up style issues and reduced some code duplication and variable naming issues.
- Fixes #193 
@johlju - would you mind reviewing this one for me when you get time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/196)
=> Fix Issues with Extension Detection on non-US Localization - Fixes #193

CHANGELOG.md, Modules/CertificateDsc.Common/CertificateDsc.Common.psm1, Tests/Integration/CertificateDsc.Common.Tests.ps1
Adds support for importing chained certificates (ex. .p7b) back into the CertificateImport resource.  This functionality was lost in a recent change that caused all Set calls to CertificateImport to use the Import-CertificateEx function.
- Fixes #192 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/197)
=> CertificateImport: Support chained certificates (Fixes #192)

CHANGELOG.md, DSCResources/MSFT_CertReq/MSFT_CertReq.psm1, Examples/Resources/CertReq/1-CertReq_RequestAltSSLCert_Config.ps1, Examples/Resources/CertReq/2-CertReq_RequestSSLCert_Config.ps1, Tests/Integration/MSFT_CertReq.Integration.Tests.ps1, Tests/Unit/MSFT_CertReq.Tests.ps1
This PR changes CertReq so that it doesn't require the ProviderName to be encapsulated in double quotes. It will still work correctly even if it is encapsulated.
- Fixes #185
@johlju - would you mind reviewing this one when you get a moment?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/201)
=> CertReq: Fix Error when ProviderName not Encapsulated in Quotes - Fixes #185

CHANGELOG.md, DSCResources/MSFT_CertReq/MSFT_CertReq.psm1, Tests/Unit/MSFT_CertReq.Tests.ps1
Removed hardcoded reference in Compare-CertificateIssuer and Get-TargetResource.
This should fix an issue with third party CA's/HSM's which does not necessarily format the CN in the same order as a Microsoft CA does. This issue caused the CA to issue a new cert each time DSC was run even though a valid certificate existed.
- Fixes #207 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/209)
=> CertReq: Removed hardcoded references

CHANGELOG.md, DSCResources/MSFT_CertReq/MSFT_CertReq.psm1, Modules/CertificateDsc.Common/CertificateDsc.Common.psm1
This PR corrects the CHANGELOG.MD and also fixes some minor problems:
- Corrected name of working path to remove `x` - fixes [Issue #211](https://github.com/PowerShell/CertificateDsc/issues/211).
- Fix bug `Find-Certificate` when invalid certificate path is passed - fixes
[Issue #208](https://github.com/PowerShell/CertificateDsc/issues/208).
- Fixes #208
- Fixes #211
@johlju - would you mind reviewing this? It should be a quick one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/212)
=> CHANGELOG.MD and Minor Corrections - Fixes #211, #208

CHANGELOG.md, source/DSCResources/DSC_PfxImport/README.md, source/Examples/Resources/PfxImport/5-PfxImport_InstallPFXAdministrator_Config.ps1
This PR just adds a new example showing how to use PsDscRunAsCredential to import a certificate with a private key.
- Fixes #213
@johlju - would you mind reviewing if you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/certificatedsc/238)
=> Added example for PFXImport - Fixes #213

CHANGELOG.md, source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1, source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.schema.mof, source/DSCResources/DSC_CertificateImport/en-US/DSC_CertificateImport.strings.psd1, source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1, source/DSCResources/DSC_PfxImport/DSC_PfxImport.schema.mof, source/DSCResources/DSC_PfxImport/en-US/DSC_PfxImport.strings.psd1, source/Examples/Resources/CertificateImport/3-CertificateImport_WithContent_Config.ps1, source/Examples/Resources/PfxImport/6-PfxImport_InstallPFXFromContent_Config.ps1, source/Modules/CertificateDsc.Common/CertificateDsc.Common.psm1, tests/Integration/DSC_CertificateImport.Integration.Tests.ps1, tests/Integration/DSC_CertificateImport.config.ps1, tests/Integration/DSC_PfxImport.Integration.Tests.ps1, tests/Integration/DSC_PfxImport.config.ps1, tests/Unit/CertificateDsc.Common.Tests.ps1, tests/Unit/DSC_CertificateImport.Tests.ps1, tests/Unit/DSC_PfxImport.Tests.ps1
Updated the resources ImportPFX and ImportCertificate with the following:
* Added Base64Content parameter to specify the content of a PFX file that can be included in the configuration MOF.
* Added Base64Content parameter to specify the content of a certificate file that can be included in the configuration MOF.
* Updated unit and integration tests
- Issue #241 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/certificatedsc/242)
=> CertificateDsc: Add content parameter to ImportPFX and ImportCertificate resources

CHANGELOG.md, source/Modules/CertificateDsc.Common/CertificateDsc.Common.psm1, tests/Integration/CertificateDsc.Common.Tests.ps1, tests/Integration/DSC_CertificateExport.Integration.Tests.ps1
Importing PFX certificates to the local machine certificate path and the resource uses the function 'Import-PfxCertificateEx' from the common module results in the private key being installed in the users key store location rather than the machine path. The result of using the native 'Import-PfxCertificate' cmdlet is that the private key is stored in the same path as the public key import location.
- Fixes #248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/certificatedsc/249)
=> DSC_ImportPfx: Update private key import location for LocalMachine using Import-PfxCertificateEx

CHANGELOG.md, RequiredModules.psd1, azure-pipelines.yml, source/DSCResources/DSC_CertReq/DSC_CertReq.psm1, source/DSCResources/DSC_CertReq/DSC_CertReq.schema.mof, source/DSCResources/DSC_CertReq/en-US/DSC_CertReq.strings.psd1, tests/Unit/DSC_CertReq.Tests.ps1
*Breaking Change*: Support multiple certificates with the same `issuer` and `subject` by making `friendlyName` a mandatory (key) parameter
Prevent existing certificates with non-matching `friendlyName` and `template` being considered as existing desired certificates; This resolves problems where an incorrect existing certificate is compared with the desired state and `Test-TargetResource` consequentially returns `$false`.
- Fixes #121
- Fixes #269
- Replaces PR #206 
file CHANGELOG.md. Entry should say what was changed and how that
affects users (if applicable), and reference the issue being resolved
(if applicable).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> BREAKING CHANGE: CertReq: Improve certificate match selectivity

CHANGELOG.md, azure-pipelines.yml
This is a quick fix to the AzurePipeline.yml to force the pipeline to stick to v5.* of Gitversion
Longer term we should move as much of similar config into a template.yml that we can call instead of this being something that we need to manage across all the DSCCommunity Repos 1 by 1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/CertificateDsc/276)
=> force setting to gitversion 5.*
