- DSCResources/MSFT_xCertificateImport/MSFT_xCertificateImport.psm1
- DSCResources/MSFT_xCertificateImport/MSFT_xCertificateImport.schema.mof
- Examples/Sample_xCertificateImport_MinimalUsage.ps1
- ReadMe.md
- Tests/MSFT_xCertificateImport.tests.ps1
- Tests/MSFT_xPfxImport.tests.ps1
Implemented the additional resource called xCertificateImport based on pull request #16 (made by @allansson) which was sadly closed due to inactivity. 
This pull request also contains the changes made in pull request #19. To make sure the xPfxImport and xCertificateImport resources look alike.
This closes #15.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/20)
> Implemented the xCertificateImport DSC Resource based on pull request #16 and #19

- DSCResources/MSFT_xCertificateImport/MSFT_xCertificateImport.psm1
- DSCResources/MSFT_xCertificateImport/MSFT_xCertificateImport.schema.mof
- DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.psm1
- DSCResources/MSFT_xPfxImport/MSFT_xPfxImport.schema.mof
- Examples/Sample_xCertificateImport_MinimalUsage.ps1
- ReadMe.md
- Tests/MSFT_xCertificateImport.tests.ps1
- Tests/MSFT_xPfxImport.tests.ps1
- appveyor.yml
- xCertificate.psd1
Releasing version 2.0.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/22)
> Release of version 2.0.0.0 of xCertificate

- ReadMe.md
- appveyor.yml
- xCertificate.psd1
Releasing version 2.1.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/23)
> Release of version 2.1.0.0 of xCertificate

- ReadMe.md
- appveyor.yml
This is for PowerShell/DscResources#147.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/24)
> Using PSGallery to Install Pester in AppVeyor File

- Examples/Resources/xPfxImport/2-MinimalUsage.ps1
Added mandatory properties required by the DSC resource
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/58)
> Updated example for mandatory properties

- ReadMe.md
Updated example on Readme to include the mandatory items required by the DSC Resource
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/59)
> Updated example for xPfxImport

- ReadMe.md
#59 
#58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/60)
> Updated Readme for example change

- .vscode/settings.json
I didn't update the changelog for this because it already contains an unreleased entry for add the settings.json file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/76)
> Added powershell.codeFormatting.preset to .vscode\settings.json - Fixes #75

- .MetaTestOptIn.json
- .codecov.yml
- Examples/Resources/xPfxImport/1-IIS_WebSite.ps1
- Examples/Resources/xPfxImport/2-MinimalUsage.ps1
- ReadMe.md
- appveyor.yml
This adds support for CodeCov.io code coverage analysis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/79)
> Enable CodeCov.io Support - Fixes #78

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- ReadMe.md
Files copied from xFailOverCluster with resource names corrected.
Requesting review from @Johlju
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/90)
> Added .github support files - Fixes #89

- .MetaTestOptIn.json
- Examples/Resources/xCertificateExport/1-CertByFriendlyName.ps1
- Modules/CertificateDsc.Common/CertificateDSc.Common.psm1
- Modules/CertificateDsc.ResourceHelper/CertificateDsc.ResourceHelper.psm1
- ReadMe.md
- Tests/TestHelpers/CommonTestHelper.psm1
Several of the module files were using UTF8 with BOM encoding. This PR converts them to UTF8 encoding. It also opts into the common tests:
"Common Tests - Validate Module Files"
"Common Tests - Validate Script Files"
Fixes #87
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/93)
> Converted Files with UTF8 BOM to UTF8 and Opted into Common Tests - Fixes #87

- Modules/CertificateDsc.Common/CertificateDSc.Common.psm1
$configContext.ToString() for returning System.String instead of System.DirectoryServices.PropertyValueCollection
$cdpContainer = [ADSI]('LDAP://CN=CDP,CN=Public Key Services,CN=Services,{0}' -f $configContext) returns an error:
format-default : The following exception occurred while retrieving member "distinguishedName": "An invalid dn syntax has been specified.
"
+ CategoryInfo          : NotSpecified: (:) [format-default], ExtendedTypeSystemException
+ FullyQualifiedErrorId : CatchFromBaseGetMember,Microsoft.PowerShell.Commands.FormatDefaultCommand
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> $configContext.ToString()

- CHANGELOG.md
- Tests/Integration/MSFT_xCertReq.Integration.Tests.ps1
- Tests/Integration/MSFT_xCertificateExport.Integration.Tests.ps1
- Tests/Integration/MSFT_xCertificateImport.Integration.Tests.ps1
- Tests/Integration/MSFT_xPfxImport.Integration.Tests.ps1
- Tests/Integration/MSFT_xWaitForCertificateServices.Integration.Tests.ps1
- Tests/Integration/ModuleConflict.Tests.ps1
- Tests/Unit/CertificateDsc.Common.Tests.ps1
- Tests/Unit/MSFT_xCertReq.Tests.ps1
- Tests/Unit/MSFT_xCertificateExport.Tests.ps1
- Tests/Unit/MSFT_xCertificateImport.Tests.ps1
- Tests/Unit/MSFT_xPfxImport.Tests.ps1
- Tests/Unit/MSFT_xWaitForCertificateServices.Tests.ps1
Update the pester tests to meet V4 guidelines.
Fixes #105
**Task list:**
@Johlju - would you mind reviewing? Hopefully this one is pretty simple.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xcertificate/109)
> Updated tests to meet Pester V4 guidelines - Fixes #105

- CHANGELOG.md
- Modules/CertificateDsc/DSCResources/MSFT_PfxImport/MSFT_PfxImport.psm1
- Modules/CertificateDsc/DSCResources/MSFT_PfxImport/en-US/MSFT_PfxImport.strings.psd1
- Modules/CertificateDsc/Modules/CertificateDsc.Common/CertificateDSc.Common.psm1
- Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1
- Tests/Unit/CertificateDsc.Common.Tests.ps1
- Tests/Unit/MSFT_PfxImport.Tests.ps1
This PR changes PfxImport so that it will reimport PFX if private key is not installed.
It also refactors some code in PfxImport and moves it into CertificateDsc.Common. It also improves the unit and integration tests to meet standards and improve coverage.
Full details:
- PfxImport:
- Changed so that PFX will be reimported if private key is not
installed - fixes [Issue #129](https://github.com/PowerShell/CertificateDsc/issues/129).
- Corrected to meet style guidelines.
- Corrected path parameter description - fixes [Issue #125](https://github.com/PowerShell/CertificateDsc/issues/125).
- Refactored to remove code duplication by creating Get-CertificateStorePath.
- Improved unit tests to meet standards and provide better coverage.
- Improved integration …
> PfxImport - Enable Re-import if Private Key not installed - Fixes #129

- CHANGELOG.md
This PR corrects the CHANGELOG.MD that got out of sync when PR #130 was merged.
- Fixes #132
**Task list:**
@johlju - could you review this one? It just corrects a previous PR merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/133)
> Fix Merge Issue in CHANGELOG.MD from PR #130

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- README.md
Moved Code of Conduct to separate file.
- Fixes #139
**Task list:**
@Johlju - would you mind reviewing? Should be just standard Code of Conduct change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/140)
> Moved Code of Conduct to separate file - Fixes #139

- CHANGELOG.md
- appveyor.yml
When the folder structure was refactored, some common test was opt-out because there is missing parameter in the appveyor.yml.
n/a
**Task list:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/152)
> Remove exclusion of all tags

- CHANGELOG.md
- DSCResources/MSFT_PfxImport/README.md
Adds requirements to README.MD for PfxImport to define support for PFX cryptographic algorithims.
Fixes #153
**Task list:**
@johlju - would you mind reviewing?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/154)
> Updated PfxImport README.MD with requirements - Fixes #153

- .vscode/analyzersettings.psd1
- .vscode/settings.json
- CHANGELOG.md
Added .VSCode PSSA Settings to apply DSC Specific rules.
- Fixes #157
@johlju - would you mind reviewing? Should be a simple one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/158)
> Added .VSCode PSSA Settings - Fixes #157

- CHANGELOG.md
- LICENSE
Update LICENSE file to match the Microsoft Open Source Team standard.
In new repositories that are created by the Microsoft Open Source Team, the LICENSE file does not contain the year in the copyright "header".
- Fixes #164 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/165)
> CertificateDsc: Updated LICENSE file to match the Microsoft Open Source Team standard.

- .MetaTestOptIn.json
- CHANGELOG.md
Opts into common meta tests.
- Fixes #168 
@johlju - would you mind reviewing this one for me? Should be a quick one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/169)
> Opted into common tests - Fixes #168

- CHANGELOG.md
- CertificateDsc.psd1
- DSCResources/MSFT_CertificateImport/MSFT_CertificateImport.psm1
- Tests/Unit/MSFT_CertificateImport.Tests.ps1
Updated certificate import to only use Import-CertificateEx
-Fixes #161 
- [x ] Added an entry under the Unreleased section of the CHANGELOG.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/162)
> CertificateImport: Fix for Issue 161: Updated certificate import to only use Import-CertificateEx

- CHANGELOG.md
- appveyor.yml
This PR opts in to Example publishing to the PS Gallery.
- Fixes #177 
@johlju - would you mind reviewing? Should be trivial. Thank you as always!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/178)
> Opt-in to Example Publishing - Fixes #177

- CHANGELOG.md
- appveyor.yml
This PR fixes the example publish to PS Gallery by adding the missing environment variable to AppVeyor.yml. Also corrected a minor layout issue in the Changelog.md.
#187 
@johlju - would you mind reviewing for me? Should be a small one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/188)
> Fix example publish to PS Gallery - Fixes #187 

- CHANGELOG.md
- DSCResources/MSFT_CertificateImport/MSFT_CertificateImport.psm1
- DSCResources/MSFT_CertificateImport/MSFT_CertificateImport.schema.mof
- DSCResources/MSFT_CertificateImport/en-US/MSFT_CertificateImport.strings.psd1
- DSCResources/MSFT_PfxImport/MSFT_PfxImport.psm1
- DSCResources/MSFT_PfxImport/MSFT_PfxImport.schema.mof
- DSCResources/MSFT_PfxImport/en-US/MSFT_PfxImport.strings.psd1
- Examples/Resources/CertificateImport/2-CertificateImport_FriendlyName_Config.ps1
- Examples/Resources/PfxImport/4-PfxImport_FriendlyName_Config.ps1
- Modules/CertificateDsc.Common/CertificateDsc.Common.psm1
- Tests/Integration/MSFT_CertificateImport.Integration.Tests.ps1
- Tests/Integration/MSFT_CertificateImport.config.ps1
- Tests/Integration/MSFT_PfxImport.Integration.Tests.ps1
- Tests/Integration/MSFT_PfxImport.config.ps1
- Tests/Unit/CertificateDsc.Common.Tests.ps1
- Tests/Unit/MSFT_CertificateImport.Tests.ps1
- Tests/Unit/MSFT_PfxImport.Tests.ps1
Added FriendlyName parameter to ImportCertificate and ImportPfx.
- Fixes #194 
@johlju - would you mind reviewing this one for me when you get a moment?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/certificatedsc/203)
> Added FriendlyName parameter to ImportCertificate and ImportPfx - Fixes #194

- CHANGELOG.md
- GitVersion.yml
- README.md
This PR fixes the badges in the README.MD to point at the new pipeline and corrects the next version number in the GitVersion.
@johlju - could you review this one for me? Should be an easy one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/certificatedsc/222)
> Fix badges and Version number

- CHANGELOG.md
- source/DSCResources/DSC_CertReq/DSC_CertReq.psm1
- source/DSCResources/DSC_CertReq/en-US/DSC_CertReq.strings.psd1
- tests/Unit/DSC_CertReq.Tests.ps1
Adds simple error handling for certreq call
Fixes #224
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/certificatedsc/231)
> add certreq basic error handling

- CHANGELOG.md
- RequiredModules.psd1
- Pin `Pester` module to 4.10.1 because Pester 5.0 is missing code
coverage - Fixes [Issue #233](https://github.com/dsccommunity/CertificateDsc/issues/233).
- Fixes #233 
@johlju - could you review this one when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/certificatedsc/234)
> Pin Pester 4.10.1 - Fixes #233

- CHANGELOG.md
- build.yaml
- source/WikiSource/Home.md
Automate publishing of Wiki content.
- Fixes #235
@johlju - would you mind reviewing this when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/certificatedsc/236)
> Automate Wiki Publish - Issue #235

- CHANGELOG.md
- GitVersion.yml
- README.md
- azure-pipelines.yml
- build.yaml
- source/CertificateDsc.psd1
- source/Examples/Resources/CertReq/1-CertReq_RequestAltSSLCert_Config.ps1
- source/Examples/Resources/CertReq/2-CertReq_RequestSSLCert_Config.ps1
- source/Examples/Resources/CertificateExport/1-CertificateExport_CertByFriendlyName_Config.ps1
- source/Examples/Resources/CertificateExport/2-CertificateExport_PfxByFriendlyName_Config.ps1
- source/Examples/Resources/CertificateImport/1-CertificateImport_MinimalUsage_Config.ps1
- source/Examples/Resources/CertificateImport/2-CertificateImport_FriendlyName_Config.ps1
- source/Examples/Resources/PfxImport/1-PfxImport_InstallPFXForWebSite_Config.ps1
- source/Examples/Resources/PfxImport/2-PfxImport_InstallPFX_Config.ps1
- source/Examples/Resources/PfxImport/3-PfxImport_RemovePFX_Config.ps1
- source/Examples/Resources/PfxImport/4-PfxImport_FriendlyName_Config.ps1
- source/Examples/Resources/PfxImport/5-PfxImport_InstallPFXAdministrator_Config.ps1
- source/Examples/Resources/WaitForCertificateServices/1-WaitForCertificateServices_RequestSSLCertWithWait_Config.ps1
- source/WikiSource/Home.md
This PR is the first stage of renaming the `master` branch to `main`.
- Fixes #237 
@johlju - would you mind reviewing this when you get time? Should be simple one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/certificatedsc/243)
> Updated pipeline files to support change of master to main - Fixes #237

- CHANGELOG.md
- GitVersion.yml
This PR updates GitVersion.yml to the latest pattern.
- Fixes #245
@johlju - would you mind reviewing for me when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/certificatedsc/246)
> Update Gitversion to latest pattern - Fixes #245

- CHANGELOG.md
- README.md
- source/DSCResources/DSC_CertReq/DSC_CertReq.psm1
- source/DSCResources/DSC_CertificateExport/DSC_CertificateExport.psm1
- source/DSCResources/DSC_CertificateImport/DSC_CertificateImport.psm1
- source/DSCResources/DSC_PfxImport/DSC_PfxImport.psm1
- source/DSCResources/DSC_WaitForCertificateServices/DSC_WaitForCertificateServices.psm1
- source/Modules/CertificateDsc.Common/CertificateDsc.Common.psm1
- source/Modules/CertificateDsc.Common/en-US/CertificateDsc.Common.strings.psd1
- source/Modules/CertificateDsc.PDT/CertificateDsc.PDT.psm1
- source/Modules/CertificateDsc.PDT/en-US/CertificateDsc.PDT.strings.psd1
- tests/Integration/DSC_CertificateExport.Integration.Tests.ps1
- tests/TestHelpers/CommonTestHelper.psm1
- tests/Unit/CertificateDsc.Common.Tests.ps1
- tests/Unit/DSC_CertReq.Tests.ps1
- tests/Unit/DSC_CertificateExport.Tests.ps1
- tests/Unit/DSC_CertificateImport.Tests.ps1
- tests/Unit/DSC_PfxImport.Tests.ps1
This PR primarily removes the testing requirement to use the `New-SelfSignedCertificateEx`. This resource will no longer be able to be tested on Windows Server 2012 R2 - although the resources will still work. This is to simplify testing and remove dependencies.
I also refactored the code and tests and in the process identified an issue where FIPS support wasn't available on PS Core 6/PS 7. So, this has also been fixed.
Finally, I improved the overall resource performance by adding caching to the thumbprint hashing check code. This increases test performance significantly and speeds up CI from 45 min to 12 min.
- Changed `Test-Thumbprint` to cache supported hash algorithms to increase
performance - Fixes [Issue #221](https://github.com/dsccommunity/CertificateDsc/issues/221).
- Removed …
> Remove Test Dependency on New-SelfSignedCertificateEx - Fixes #221, #250

- CHANGELOG.md
- README.md
- RequiredModules.psd1
- azure-pipelines.yml
- build.yaml
- codecov.yml
This PR adds build coverage reporting to build pipeline. It also updates the build to use Sampler.GitHubTasks.
- Fixes #254 
- Fixes #255 
@johlju - would you mind reviewing when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/certificatedsc/256)
> Update Pipeline to Publish Code Coverage - Fixes #255

- CHANGELOG.md
- README.md
- azure-pipelines.yml
This PR corrects CHANGELOG.md and updates task to latest version.
@johlju - would you mind reviewing when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/certificatedsc/257)
> Updated pipeline tasks to latest version

- .vscode/analyzersettings.psd1
- .vscode/settings.json
- CHANGELOG.md
- GitVersion.yml
- RequiredModules.psd1
- Resolve-Dependency.ps1
- Resolve-Dependency.psd1
- azure-pipelines.yml
- build.ps1
- build.yaml
- source/Examples/README.md
This PR updates the pipeline and supporting files to the latest DSC Community pattern. It also updates the build and HQRM VM images to run on windows-latest.
- Fixes #274 
file CHANGELOG.md. Entry should say what was changed and how that
affects users (if applicable), and reference the issue being resolved
(if applicable).
Remaining N/A
Another one - thanks @johlju !
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/CertificateDsc/275)
> Update to latest CI pipeline pattern - Fixes #274

- CHANGELOG.md
- azure-pipelines.yml
- build.yaml
Windows 2019 pipeline image is going to be deprecated on 30/06/2025.
- Fixes #278 
file CHANGELOG.md. Entry should say what was changed and how that
affects users (if applicable), and reference the issue being resolved
(if applicable).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/CertificateDsc/279)
> Remove `windows-2019` pipeline image
